Repository DenverCoder1/github-readme-youtube-cards, pull requests merged in 2022-10, with the labels that each got.

#30 fix: Ensure all titles are autoescaped in svg templates
  web/app.py
Labels: bug

#37 revert: Put back ytcards.demolab.com as the default base url
  README.md
  action.py
  action.yml
Labels: chore

#41 docs(contributing): Fix action.py usage instructions
  CONTRIBUTING.md
Labels: documentation

#42 refactor: Move large data to resources instead of svg
  api/index.py
  api/templates/error.svg
  api/templates/main.svg
  api/templates/resources/error.jpg
  api/templates/resources/roboto.css
  api/utils.py
  tests/test_utils.py
Labels: refactor

#43 refactor: Removed 'required' attributes and simplify validation
  api/index.py
  api/validate.py
  tests/test_validate.py
  tox.ini
Labels: refactor

#44 ci: Add test cases for rendering the cards
  api/__init__.py
  tests/conftest.py
  tests/test_app.py
Labels: chore

#45 refactor: Use pytest fixtures for mock request
  tests/conftest.py
  tests/test_validate.py
Labels: chore, refactor

#47 ci: Add unit tests for parse_videos and FileUpdater
  action.py
  tests/test_action.py
Labels: chore

#49 feat: Add Hebrew translations and RTL support
  api/index.py
  api/locale/he.yml
  api/templates/main.svg
  tests/test_app.py
Labels: enhancement

#52 refactor: Use yaml to mark languages as rtl
  api/index.py
  api/locale/he.yml
  api/utils.py
Labels: refactor

#51 feat: Added Indonesian Translations to YouTube Cards
  api/locale/id.yml
Labels: enhancement

#56 chore: Bump version to 1.3.0
  pyproject.toml
Labels: chore

#57 chore: Improvements to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: chore

#58 chore: Create dependabot.yml
  .github/dependabot.yml
Labels: chore

#59 chore(deps): Use requirements file in action.yml and fixed deps
  action.yml
  requirements-action.txt
  requirements.txt
Labels: dependencies

#53 feat: Added Persian (Farsi) translations
  api/locale/fa.yml
Labels: enhancement

#67 feat: Use Babel for numbers and dates to support many locales
  api/index.py
  api/locale/bn.yml
  api/locale/en.yml
  api/locale/fa.yml
  api/locale/fr.yml
  api/locale/he.yml
  api/locale/hi.yml
  api/locale/id.yml
  api/locale/ur.yml
  api/utils.py
  api/validate.py
  requirements.txt
  tests/test_app.py
  tests/test_utils.py
Labels: feature

#70 feat: Added Japanese translations
  api/locale/ja.yml
Labels: feature

#72 ci: Remove unused imports with autoflake
  .pre-commit-config.yaml
  tests/test_utils.py
Labels: chore
